### ISSUE TITLE
Why do the RxAndroidPlugins methods need to be invoked with reflection?

### ISSUE THREAD

**Issue by tomjegan** [technoir42/rxjava-junit#1]
As per title. Is there a specific reason for this?

**Comment by technoir42** [comment]
I wanted to have a single library for both JVM and Android. RxAndroid is packaged as AAR so I can't link to it statically.

**Comment by tomjegan** [comment]
Gotcha! That makes sense!

Thank you _(sorry couldn't flag this as a question originally)_
